plugins {
    id "com.android.application"
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace "ir.nexsport.app"
    compileSdk 33

    defaultConfig {
        applicationId "ir.nexsport.app"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "2.0.0"
        resConfigs "fa"
    }

    signingConfigs {
        if (keystorePropertiesFile.exists()) {
            release {
                keyAlias keystoreProperties["keyAlias"]
                keyPassword keystoreProperties["keyPassword"]
                storeFile rootProject.file(keystoreProperties["storeFile"])
                storePassword keystoreProperties["storePassword"]
                enableV1Signing true
                enableV2Signing true
            }
        }
    }

    buildTypes {
            release {
                minifyEnabled false
                if (keystorePropertiesFile.exists()) {
                    signingConfig signingConfigs.release
                }
            }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
}
